# Generated by Django 3.2.3 on 2021-05-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testers',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='uid')),
                ('age', models.IntegerField(verbose_name='age')),
                ('gender', models.BooleanField(default=True, verbose_name='gender')),
            ],
            options={
                'db_table': 'testers',
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FilePathField(max_length=128, path=['C:\\files\\Edinburgh\\Dissertation\\code\\svftest\\audios'], verbose_name='audio path')),
                ('category', models.CharField(max_length=64, verbose_name='category')),
                ('test_time', models.DateTimeField(auto_now=True, verbose_name='test time')),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TestModel.testers')),
            ],
            options={
                'db_table': 'records',
            },
        ),
    ]
