# Generated by Django 3.2.3 on 2021-05-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='records',
            unique_together={('category', 'uid')},
        ),
    ]
