# Generated by Django 3.2.3 on 2021-05-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_alter_records_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='tester',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='TestModel.testers'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='records',
            unique_together={('category', 'tester')},
        ),
        migrations.RemoveField(
            model_name='records',
            name='uid',
        ),
    ]
